//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Yu-Gi-Oh_Loader Plugins/Yu-Gi-Oh-Effects/Script/EffectScript.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace WolfEx.EffectScriptGenerated {
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public partial class EffectScriptParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, T__14=15, T__15=16, T__16=17, 
		T__17=18, T__18=19, T__19=20, T__20=21, T__21=22, T__22=23, T__23=24, 
		T__24=25, T__25=26, T__26=27, T__27=28, T__28=29, T__29=30, T__30=31, 
		T__31=32, T__32=33, T__33=34, T__34=35, T__35=36, T__36=37, T__37=38, 
		T__38=39, T__39=40, T__40=41, T__41=42, T__42=43, T__43=44, T__44=45, 
		T__45=46, T__46=47, T__47=48, T__48=49, T__49=50, T__50=51, T__51=52, 
		NUMBER=53, IDENT=54, STRING=55, WS=56, LINE_COMMENT=57;
	public const int
		RULE_script = 0, RULE_effect = 1, RULE_effectBody = 2, RULE_limit = 3, 
		RULE_trigger = 4, RULE_triggerName = 5, RULE_chain = 6, RULE_action = 7, 
		RULE_drawAction = 8, RULE_searchAction = 9, RULE_reviveAction = 10, RULE_destroyAction = 11, 
		RULE_scope = 12, RULE_sendAction = 13, RULE_gainAction = 14, RULE_burnAction = 15, 
		RULE_graveyard = 16, RULE_side = 17, RULE_selector = 18, RULE_kind = 19, 
		RULE_condition = 20, RULE_field = 21, RULE_op = 22, RULE_value = 23;
	public static readonly string[] ruleNames = {
		"script", "effect", "effectBody", "limit", "trigger", "triggerName", "chain", 
		"action", "drawAction", "searchAction", "reviveAction", "destroyAction", 
		"scope", "sendAction", "gainAction", "burnAction", "graveyard", "side", 
		"selector", "kind", "condition", "field", "op", "value"
	};

	private static readonly string[] _LiteralNames = {
		null, "'effect'", "'{'", "'}'", "';'", "'once_per_turn'", "'on'", "':'", 
		"'normal_summoned'", "'special_summoned'", "'summoned'", "'normal_or_special_summoned'", 
		"'flip'", "'destroyed_by_battle'", "'sent_to_grave'", "'sent_from_field_to_grave'", 
		"'then'", "'draw'", "'('", "')'", "'search'", "'deck'", "','", "'revive'", 
		"'destroy'", "'all'", "'target'", "'send_to_grave'", "'gain_lp'", "'burn'", 
		"'grave'", "'opponent_grave'", "'either_grave'", "'own'", "'opponent'", 
		"'any'", "'where'", "'and'", "'monster'", "'spell'", "'trap'", "'card'", 
		"'race'", "'attribute'", "'level'", "'atk'", "'archetype'", "'name'", 
		"'='", "'<='", "'>='", "'<'", "'>'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, "NUMBER", "IDENT", "STRING", "WS", "LINE_COMMENT"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "EffectScript.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static EffectScriptParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public EffectScriptParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public EffectScriptParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ScriptContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public EffectContext effect() {
			return GetRuleContext<EffectContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(EffectScriptParser.Eof, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public EffectBodyContext effectBody() {
			return GetRuleContext<EffectBodyContext>(0);
		}
		public ScriptContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_script; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitScript(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ScriptContext script() {
		ScriptContext _localctx = new ScriptContext(Context, State);
		EnterRule(_localctx, 0, RULE_script);
		try {
			State = 54;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__0:
				EnterOuterAlt(_localctx, 1);
				{
				State = 48;
				effect();
				State = 49;
				Match(Eof);
				}
				break;
			case T__5:
			case T__16:
			case T__19:
			case T__22:
			case T__23:
			case T__26:
			case T__27:
			case T__28:
				EnterOuterAlt(_localctx, 2);
				{
				State = 51;
				effectBody();
				State = 52;
				Match(Eof);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EffectContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public EffectBodyContext effectBody() {
			return GetRuleContext<EffectBodyContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(EffectScriptParser.STRING, 0); }
		public EffectContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_effect; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEffect(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public EffectContext effect() {
		EffectContext _localctx = new EffectContext(Context, State);
		EnterRule(_localctx, 2, RULE_effect);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 56;
			Match(T__0);
			State = 58;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==STRING) {
				{
				State = 57;
				Match(STRING);
				}
			}

			State = 60;
			Match(T__1);
			State = 61;
			effectBody();
			State = 62;
			Match(T__2);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EffectBodyContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ChainContext chain() {
			return GetRuleContext<ChainContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public TriggerContext trigger() {
			return GetRuleContext<TriggerContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public LimitContext limit() {
			return GetRuleContext<LimitContext>(0);
		}
		public EffectBodyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_effectBody; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEffectBody(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public EffectBodyContext effectBody() {
		EffectBodyContext _localctx = new EffectBodyContext(Context, State);
		EnterRule(_localctx, 4, RULE_effectBody);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 65;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__5) {
				{
				State = 64;
				trigger();
				}
			}

			State = 67;
			chain();
			State = 69;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__3) {
				{
				State = 68;
				Match(T__3);
				}
			}

			State = 72;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__4) {
				{
				State = 71;
				limit();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LimitContext : ParserRuleContext {
		public LimitContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_limit; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLimit(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LimitContext limit() {
		LimitContext _localctx = new LimitContext(Context, State);
		EnterRule(_localctx, 6, RULE_limit);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 74;
			Match(T__4);
			State = 76;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__3) {
				{
				State = 75;
				Match(T__3);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TriggerContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public TriggerNameContext triggerName() {
			return GetRuleContext<TriggerNameContext>(0);
		}
		public TriggerContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_trigger; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTrigger(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TriggerContext trigger() {
		TriggerContext _localctx = new TriggerContext(Context, State);
		EnterRule(_localctx, 8, RULE_trigger);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 78;
			Match(T__5);
			State = 79;
			triggerName();
			State = 80;
			Match(T__6);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TriggerNameContext : ParserRuleContext {
		public TriggerNameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_triggerName; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTriggerName(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TriggerNameContext triggerName() {
		TriggerNameContext _localctx = new TriggerNameContext(Context, State);
		EnterRule(_localctx, 10, RULE_triggerName);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 82;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 65280L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ChainContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ActionContext[] action() {
			return GetRuleContexts<ActionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ActionContext action(int i) {
			return GetRuleContext<ActionContext>(i);
		}
		public ChainContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_chain; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitChain(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ChainContext chain() {
		ChainContext _localctx = new ChainContext(Context, State);
		EnterRule(_localctx, 12, RULE_chain);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 84;
			action();
			State = 89;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__15) {
				{
				{
				State = 85;
				Match(T__15);
				State = 86;
				action();
				}
				}
				State = 91;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ActionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public DrawActionContext drawAction() {
			return GetRuleContext<DrawActionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public SearchActionContext searchAction() {
			return GetRuleContext<SearchActionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ReviveActionContext reviveAction() {
			return GetRuleContext<ReviveActionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public DestroyActionContext destroyAction() {
			return GetRuleContext<DestroyActionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public GainActionContext gainAction() {
			return GetRuleContext<GainActionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public BurnActionContext burnAction() {
			return GetRuleContext<BurnActionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public SendActionContext sendAction() {
			return GetRuleContext<SendActionContext>(0);
		}
		public ActionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_action; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAction(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ActionContext action() {
		ActionContext _localctx = new ActionContext(Context, State);
		EnterRule(_localctx, 14, RULE_action);
		try {
			State = 99;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__16:
				EnterOuterAlt(_localctx, 1);
				{
				State = 92;
				drawAction();
				}
				break;
			case T__19:
				EnterOuterAlt(_localctx, 2);
				{
				State = 93;
				searchAction();
				}
				break;
			case T__22:
				EnterOuterAlt(_localctx, 3);
				{
				State = 94;
				reviveAction();
				}
				break;
			case T__23:
				EnterOuterAlt(_localctx, 4);
				{
				State = 95;
				destroyAction();
				}
				break;
			case T__27:
				EnterOuterAlt(_localctx, 5);
				{
				State = 96;
				gainAction();
				}
				break;
			case T__28:
				EnterOuterAlt(_localctx, 6);
				{
				State = 97;
				burnAction();
				}
				break;
			case T__26:
				EnterOuterAlt(_localctx, 7);
				{
				State = 98;
				sendAction();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DrawActionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER() { return GetToken(EffectScriptParser.NUMBER, 0); }
		public DrawActionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_drawAction; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDrawAction(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DrawActionContext drawAction() {
		DrawActionContext _localctx = new DrawActionContext(Context, State);
		EnterRule(_localctx, 16, RULE_drawAction);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 101;
			Match(T__16);
			State = 102;
			Match(T__17);
			State = 103;
			Match(NUMBER);
			State = 104;
			Match(T__18);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SearchActionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public SelectorContext selector() {
			return GetRuleContext<SelectorContext>(0);
		}
		public SearchActionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_searchAction; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSearchAction(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SearchActionContext searchAction() {
		SearchActionContext _localctx = new SearchActionContext(Context, State);
		EnterRule(_localctx, 18, RULE_searchAction);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 106;
			Match(T__19);
			State = 107;
			Match(T__17);
			State = 108;
			Match(T__20);
			State = 111;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__21) {
				{
				State = 109;
				Match(T__21);
				State = 110;
				selector();
				}
			}

			State = 113;
			Match(T__18);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ReviveActionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public GraveyardContext graveyard() {
			return GetRuleContext<GraveyardContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public SelectorContext selector() {
			return GetRuleContext<SelectorContext>(0);
		}
		public ReviveActionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_reviveAction; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitReviveAction(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ReviveActionContext reviveAction() {
		ReviveActionContext _localctx = new ReviveActionContext(Context, State);
		EnterRule(_localctx, 20, RULE_reviveAction);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 115;
			Match(T__22);
			State = 116;
			Match(T__17);
			State = 117;
			graveyard();
			State = 120;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__21) {
				{
				State = 118;
				Match(T__21);
				State = 119;
				selector();
				}
			}

			State = 122;
			Match(T__18);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DestroyActionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ScopeContext scope() {
			return GetRuleContext<ScopeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public SideContext side() {
			return GetRuleContext<SideContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public SelectorContext selector() {
			return GetRuleContext<SelectorContext>(0);
		}
		public DestroyActionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_destroyAction; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDestroyAction(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DestroyActionContext destroyAction() {
		DestroyActionContext _localctx = new DestroyActionContext(Context, State);
		EnterRule(_localctx, 22, RULE_destroyAction);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 124;
			Match(T__23);
			State = 125;
			Match(T__17);
			State = 126;
			scope();
			State = 129;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,10,Context) ) {
			case 1:
				{
				State = 127;
				Match(T__21);
				State = 128;
				side();
				}
				break;
			}
			State = 133;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__21) {
				{
				State = 131;
				Match(T__21);
				State = 132;
				selector();
				}
			}

			State = 135;
			Match(T__18);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ScopeContext : ParserRuleContext {
		public ScopeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_scope; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitScope(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ScopeContext scope() {
		ScopeContext _localctx = new ScopeContext(Context, State);
		EnterRule(_localctx, 24, RULE_scope);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 137;
			_la = TokenStream.LA(1);
			if ( !(_la==T__24 || _la==T__25) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SendActionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public SelectorContext selector() {
			return GetRuleContext<SelectorContext>(0);
		}
		public SendActionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_sendAction; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSendAction(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SendActionContext sendAction() {
		SendActionContext _localctx = new SendActionContext(Context, State);
		EnterRule(_localctx, 26, RULE_sendAction);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 139;
			Match(T__26);
			State = 140;
			Match(T__17);
			State = 141;
			Match(T__20);
			State = 144;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__21) {
				{
				State = 142;
				Match(T__21);
				State = 143;
				selector();
				}
			}

			State = 146;
			Match(T__18);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class GainActionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER() { return GetToken(EffectScriptParser.NUMBER, 0); }
		public GainActionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_gainAction; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitGainAction(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public GainActionContext gainAction() {
		GainActionContext _localctx = new GainActionContext(Context, State);
		EnterRule(_localctx, 28, RULE_gainAction);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 148;
			Match(T__27);
			State = 149;
			Match(T__17);
			State = 150;
			Match(NUMBER);
			State = 151;
			Match(T__18);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BurnActionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER() { return GetToken(EffectScriptParser.NUMBER, 0); }
		public BurnActionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_burnAction; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBurnAction(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BurnActionContext burnAction() {
		BurnActionContext _localctx = new BurnActionContext(Context, State);
		EnterRule(_localctx, 30, RULE_burnAction);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 153;
			Match(T__28);
			State = 154;
			Match(T__17);
			State = 155;
			Match(NUMBER);
			State = 156;
			Match(T__18);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class GraveyardContext : ParserRuleContext {
		public GraveyardContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_graveyard; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitGraveyard(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public GraveyardContext graveyard() {
		GraveyardContext _localctx = new GraveyardContext(Context, State);
		EnterRule(_localctx, 32, RULE_graveyard);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 158;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 7516192768L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SideContext : ParserRuleContext {
		public SideContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_side; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSide(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SideContext side() {
		SideContext _localctx = new SideContext(Context, State);
		EnterRule(_localctx, 34, RULE_side);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 160;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 60129542144L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SelectorContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public KindContext kind() {
			return GetRuleContext<KindContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ConditionContext[] condition() {
			return GetRuleContexts<ConditionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ConditionContext condition(int i) {
			return GetRuleContext<ConditionContext>(i);
		}
		public SelectorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_selector; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSelector(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SelectorContext selector() {
		SelectorContext _localctx = new SelectorContext(Context, State);
		EnterRule(_localctx, 36, RULE_selector);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 185;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__37:
			case T__38:
			case T__39:
			case T__40:
				{
				State = 162;
				kind();
				State = 172;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==T__35) {
					{
					State = 163;
					Match(T__35);
					State = 164;
					condition();
					State = 169;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
					while (_la==T__36) {
						{
						{
						State = 165;
						Match(T__36);
						State = 166;
						condition();
						}
						}
						State = 171;
						ErrorHandler.Sync(this);
						_la = TokenStream.LA(1);
					}
					}
				}

				}
				break;
			case T__35:
			case T__41:
			case T__42:
			case T__43:
			case T__44:
			case T__45:
			case T__46:
				{
				State = 175;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==T__35) {
					{
					State = 174;
					Match(T__35);
					}
				}

				State = 177;
				condition();
				State = 182;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__36) {
					{
					{
					State = 178;
					Match(T__36);
					State = 179;
					condition();
					}
					}
					State = 184;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class KindContext : ParserRuleContext {
		public KindContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_kind; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitKind(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public KindContext kind() {
		KindContext _localctx = new KindContext(Context, State);
		EnterRule(_localctx, 38, RULE_kind);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 187;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 4123168604160L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ConditionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public FieldContext field() {
			return GetRuleContext<FieldContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public OpContext op() {
			return GetRuleContext<OpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public ConditionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_condition; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCondition(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ConditionContext condition() {
		ConditionContext _localctx = new ConditionContext(Context, State);
		EnterRule(_localctx, 40, RULE_condition);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 189;
			field();
			State = 190;
			op();
			State = 191;
			value();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FieldContext : ParserRuleContext {
		public FieldContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_field; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitField(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FieldContext field() {
		FieldContext _localctx = new FieldContext(Context, State);
		EnterRule(_localctx, 42, RULE_field);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 193;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 277076930199552L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OpContext : ParserRuleContext {
		public OpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_op; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOp(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public OpContext op() {
		OpContext _localctx = new OpContext(Context, State);
		EnterRule(_localctx, 44, RULE_op);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 195;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 8725724278030336L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ValueContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER() { return GetToken(EffectScriptParser.NUMBER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENT() { return GetToken(EffectScriptParser.IDENT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(EffectScriptParser.STRING, 0); }
		public ValueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_value; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitValue(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ValueContext value() {
		ValueContext _localctx = new ValueContext(Context, State);
		EnterRule(_localctx, 46, RULE_value);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 197;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 63050394783186944L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static int[] _serializedATN = {
		4,1,57,200,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,7,14,
		2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,2,20,7,20,2,21,7,21,
		2,22,7,22,2,23,7,23,1,0,1,0,1,0,1,0,1,0,1,0,3,0,55,8,0,1,1,1,1,3,1,59,
		8,1,1,1,1,1,1,1,1,1,1,2,3,2,66,8,2,1,2,1,2,3,2,70,8,2,1,2,3,2,73,8,2,1,
		3,1,3,3,3,77,8,3,1,4,1,4,1,4,1,4,1,5,1,5,1,6,1,6,1,6,5,6,88,8,6,10,6,12,
		6,91,9,6,1,7,1,7,1,7,1,7,1,7,1,7,1,7,3,7,100,8,7,1,8,1,8,1,8,1,8,1,8,1,
		9,1,9,1,9,1,9,1,9,3,9,112,8,9,1,9,1,9,1,10,1,10,1,10,1,10,1,10,3,10,121,
		8,10,1,10,1,10,1,11,1,11,1,11,1,11,1,11,3,11,130,8,11,1,11,1,11,3,11,134,
		8,11,1,11,1,11,1,12,1,12,1,13,1,13,1,13,1,13,1,13,3,13,145,8,13,1,13,1,
		13,1,14,1,14,1,14,1,14,1,14,1,15,1,15,1,15,1,15,1,15,1,16,1,16,1,17,1,
		17,1,18,1,18,1,18,1,18,1,18,5,18,168,8,18,10,18,12,18,171,9,18,3,18,173,
		8,18,1,18,3,18,176,8,18,1,18,1,18,1,18,5,18,181,8,18,10,18,12,18,184,9,
		18,3,18,186,8,18,1,19,1,19,1,20,1,20,1,20,1,20,1,21,1,21,1,22,1,22,1,23,
		1,23,1,23,0,0,24,0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,
		40,42,44,46,0,8,1,0,8,15,1,0,25,26,1,0,30,32,1,0,33,35,1,0,38,41,1,0,42,
		47,1,0,48,52,1,0,53,55,198,0,54,1,0,0,0,2,56,1,0,0,0,4,65,1,0,0,0,6,74,
		1,0,0,0,8,78,1,0,0,0,10,82,1,0,0,0,12,84,1,0,0,0,14,99,1,0,0,0,16,101,
		1,0,0,0,18,106,1,0,0,0,20,115,1,0,0,0,22,124,1,0,0,0,24,137,1,0,0,0,26,
		139,1,0,0,0,28,148,1,0,0,0,30,153,1,0,0,0,32,158,1,0,0,0,34,160,1,0,0,
		0,36,185,1,0,0,0,38,187,1,0,0,0,40,189,1,0,0,0,42,193,1,0,0,0,44,195,1,
		0,0,0,46,197,1,0,0,0,48,49,3,2,1,0,49,50,5,0,0,1,50,55,1,0,0,0,51,52,3,
		4,2,0,52,53,5,0,0,1,53,55,1,0,0,0,54,48,1,0,0,0,54,51,1,0,0,0,55,1,1,0,
		0,0,56,58,5,1,0,0,57,59,5,55,0,0,58,57,1,0,0,0,58,59,1,0,0,0,59,60,1,0,
		0,0,60,61,5,2,0,0,61,62,3,4,2,0,62,63,5,3,0,0,63,3,1,0,0,0,64,66,3,8,4,
		0,65,64,1,0,0,0,65,66,1,0,0,0,66,67,1,0,0,0,67,69,3,12,6,0,68,70,5,4,0,
		0,69,68,1,0,0,0,69,70,1,0,0,0,70,72,1,0,0,0,71,73,3,6,3,0,72,71,1,0,0,
		0,72,73,1,0,0,0,73,5,1,0,0,0,74,76,5,5,0,0,75,77,5,4,0,0,76,75,1,0,0,0,
		76,77,1,0,0,0,77,7,1,0,0,0,78,79,5,6,0,0,79,80,3,10,5,0,80,81,5,7,0,0,
		81,9,1,0,0,0,82,83,7,0,0,0,83,11,1,0,0,0,84,89,3,14,7,0,85,86,5,16,0,0,
		86,88,3,14,7,0,87,85,1,0,0,0,88,91,1,0,0,0,89,87,1,0,0,0,89,90,1,0,0,0,
		90,13,1,0,0,0,91,89,1,0,0,0,92,100,3,16,8,0,93,100,3,18,9,0,94,100,3,20,
		10,0,95,100,3,22,11,0,96,100,3,28,14,0,97,100,3,30,15,0,98,100,3,26,13,
		0,99,92,1,0,0,0,99,93,1,0,0,0,99,94,1,0,0,0,99,95,1,0,0,0,99,96,1,0,0,
		0,99,97,1,0,0,0,99,98,1,0,0,0,100,15,1,0,0,0,101,102,5,17,0,0,102,103,
		5,18,0,0,103,104,5,53,0,0,104,105,5,19,0,0,105,17,1,0,0,0,106,107,5,20,
		0,0,107,108,5,18,0,0,108,111,5,21,0,0,109,110,5,22,0,0,110,112,3,36,18,
		0,111,109,1,0,0,0,111,112,1,0,0,0,112,113,1,0,0,0,113,114,5,19,0,0,114,
		19,1,0,0,0,115,116,5,23,0,0,116,117,5,18,0,0,117,120,3,32,16,0,118,119,
		5,22,0,0,119,121,3,36,18,0,120,118,1,0,0,0,120,121,1,0,0,0,121,122,1,0,
		0,0,122,123,5,19,0,0,123,21,1,0,0,0,124,125,5,24,0,0,125,126,5,18,0,0,
		126,129,3,24,12,0,127,128,5,22,0,0,128,130,3,34,17,0,129,127,1,0,0,0,129,
		130,1,0,0,0,130,133,1,0,0,0,131,132,5,22,0,0,132,134,3,36,18,0,133,131,
		1,0,0,0,133,134,1,0,0,0,134,135,1,0,0,0,135,136,5,19,0,0,136,23,1,0,0,
		0,137,138,7,1,0,0,138,25,1,0,0,0,139,140,5,27,0,0,140,141,5,18,0,0,141,
		144,5,21,0,0,142,143,5,22,0,0,143,145,3,36,18,0,144,142,1,0,0,0,144,145,
		1,0,0,0,145,146,1,0,0,0,146,147,5,19,0,0,147,27,1,0,0,0,148,149,5,28,0,
		0,149,150,5,18,0,0,150,151,5,53,0,0,151,152,5,19,0,0,152,29,1,0,0,0,153,
		154,5,29,0,0,154,155,5,18,0,0,155,156,5,53,0,0,156,157,5,19,0,0,157,31,
		1,0,0,0,158,159,7,2,0,0,159,33,1,0,0,0,160,161,7,3,0,0,161,35,1,0,0,0,
		162,172,3,38,19,0,163,164,5,36,0,0,164,169,3,40,20,0,165,166,5,37,0,0,
		166,168,3,40,20,0,167,165,1,0,0,0,168,171,1,0,0,0,169,167,1,0,0,0,169,
		170,1,0,0,0,170,173,1,0,0,0,171,169,1,0,0,0,172,163,1,0,0,0,172,173,1,
		0,0,0,173,186,1,0,0,0,174,176,5,36,0,0,175,174,1,0,0,0,175,176,1,0,0,0,
		176,177,1,0,0,0,177,182,3,40,20,0,178,179,5,37,0,0,179,181,3,40,20,0,180,
		178,1,0,0,0,181,184,1,0,0,0,182,180,1,0,0,0,182,183,1,0,0,0,183,186,1,
		0,0,0,184,182,1,0,0,0,185,162,1,0,0,0,185,175,1,0,0,0,186,37,1,0,0,0,187,
		188,7,4,0,0,188,39,1,0,0,0,189,190,3,42,21,0,190,191,3,44,22,0,191,192,
		3,46,23,0,192,41,1,0,0,0,193,194,7,5,0,0,194,43,1,0,0,0,195,196,7,6,0,
		0,196,45,1,0,0,0,197,198,7,7,0,0,198,47,1,0,0,0,18,54,58,65,69,72,76,89,
		99,111,120,129,133,144,169,172,175,182,185
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace WolfEx.EffectScriptGenerated
