//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Yu-Gi-Oh_Loader Plugins/Yu-Gi-Oh-Effects/Script/EffectScript.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace WolfEx.EffectScriptGenerated {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="EffectScriptParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IEffectScriptVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="EffectScriptParser.script"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitScript([NotNull] EffectScriptParser.ScriptContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EffectScriptParser.effect"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEffect([NotNull] EffectScriptParser.EffectContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EffectScriptParser.effectBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEffectBody([NotNull] EffectScriptParser.EffectBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EffectScriptParser.limit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLimit([NotNull] EffectScriptParser.LimitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EffectScriptParser.trigger"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTrigger([NotNull] EffectScriptParser.TriggerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EffectScriptParser.triggerName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTriggerName([NotNull] EffectScriptParser.TriggerNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EffectScriptParser.chain"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitChain([NotNull] EffectScriptParser.ChainContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EffectScriptParser.action"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAction([NotNull] EffectScriptParser.ActionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EffectScriptParser.drawAction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDrawAction([NotNull] EffectScriptParser.DrawActionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EffectScriptParser.searchAction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSearchAction([NotNull] EffectScriptParser.SearchActionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EffectScriptParser.reviveAction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReviveAction([NotNull] EffectScriptParser.ReviveActionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EffectScriptParser.destroyAction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDestroyAction([NotNull] EffectScriptParser.DestroyActionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EffectScriptParser.scope"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitScope([NotNull] EffectScriptParser.ScopeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EffectScriptParser.sendAction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSendAction([NotNull] EffectScriptParser.SendActionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EffectScriptParser.gainAction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGainAction([NotNull] EffectScriptParser.GainActionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EffectScriptParser.burnAction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBurnAction([NotNull] EffectScriptParser.BurnActionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EffectScriptParser.graveyard"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGraveyard([NotNull] EffectScriptParser.GraveyardContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EffectScriptParser.side"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSide([NotNull] EffectScriptParser.SideContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EffectScriptParser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelector([NotNull] EffectScriptParser.SelectorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EffectScriptParser.kind"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKind([NotNull] EffectScriptParser.KindContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EffectScriptParser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCondition([NotNull] EffectScriptParser.ConditionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EffectScriptParser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitField([NotNull] EffectScriptParser.FieldContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EffectScriptParser.op"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOp([NotNull] EffectScriptParser.OpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EffectScriptParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValue([NotNull] EffectScriptParser.ValueContext context);
}
} // namespace WolfEx.EffectScriptGenerated
