//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Yu-Gi-Oh_Loader Plugins/Yu-Gi-Oh-Effects/Script/EffectScript.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace WolfEx.EffectScriptGenerated {
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public partial class EffectScriptParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, T__14=15, T__15=16, T__16=17, 
		T__17=18, T__18=19, T__19=20, T__20=21, T__21=22, T__22=23, T__23=24, 
		T__24=25, T__25=26, T__26=27, T__27=28, T__28=29, T__29=30, T__30=31, 
		T__31=32, T__32=33, T__33=34, T__34=35, T__35=36, T__36=37, T__37=38, 
		T__38=39, T__39=40, T__40=41, T__41=42, T__42=43, T__43=44, T__44=45, 
		T__45=46, T__46=47, T__47=48, T__48=49, T__49=50, T__50=51, T__51=52, 
		T__52=53, T__53=54, T__54=55, T__55=56, T__56=57, T__57=58, T__58=59, 
		T__59=60, T__60=61, T__61=62, T__62=63, T__63=64, T__64=65, T__65=66, 
		T__66=67, T__67=68, T__68=69, T__69=70, T__70=71, T__71=72, T__72=73, 
		T__73=74, T__74=75, T__75=76, T__76=77, T__77=78, T__78=79, T__79=80, 
		T__80=81, T__81=82, T__82=83, T__83=84, T__84=85, NUMBER=86, IDENT=87, 
		STRING=88, WS=89, LINE_COMMENT=90;
	public const int
		RULE_script = 0, RULE_asScript = 1, RULE_statPart = 2, RULE_effect = 3, 
		RULE_effectBody = 4, RULE_costClause = 5, RULE_tributeCost = 6, RULE_detachCost = 7, 
		RULE_discardCost = 8, RULE_payCost = 9, RULE_selfCost = 10, RULE_requireClause = 11, 
		RULE_condName = 12, RULE_limit = 13, RULE_trigger = 14, RULE_triggerName = 15, 
		RULE_chain = 16, RULE_action = 17, RULE_drawAction = 18, RULE_searchAction = 19, 
		RULE_reviveAction = 20, RULE_destroyAction = 21, RULE_scope = 22, RULE_sendAction = 23, 
		RULE_gainAction = 24, RULE_burnAction = 25, RULE_equipAction = 26, RULE_summonAction = 27, 
		RULE_summonZone = 28, RULE_returnAction = 29, RULE_gainAtkAction = 30, 
		RULE_salvageAction = 31, RULE_banishAction = 32, RULE_negateAction = 33, 
		RULE_negateArg = 34, RULE_graveyard = 35, RULE_side = 36, RULE_selector = 37, 
		RULE_kind = 38, RULE_condition = 39, RULE_field = 40, RULE_op = 41, RULE_value = 42;
	public static readonly string[] ruleNames = {
		"script", "asScript", "statPart", "effect", "effectBody", "costClause", 
		"tributeCost", "detachCost", "discardCost", "payCost", "selfCost", "requireClause", 
		"condName", "limit", "trigger", "triggerName", "chain", "action", "drawAction", 
		"searchAction", "reviveAction", "destroyAction", "scope", "sendAction", 
		"gainAction", "burnAction", "equipAction", "summonAction", "summonZone", 
		"returnAction", "gainAtkAction", "salvageAction", "banishAction", "negateAction", 
		"negateArg", "graveyard", "side", "selector", "kind", "condition", "field", 
		"op", "value"
	};

	private static readonly string[] _LiteralNames = {
		null, "'also'", "'as'", "'('", "')'", "'with'", "','", "';'", "'atk'", 
		"'def'", "'effect'", "'{'", "'}'", "'cost'", "':'", "'tribute'", "'detach'", 
		"'discard'", "'pay_lp'", "'banish_self'", "'discard_self'", "'tribute_self'", 
		"'if'", "'no_monsters'", "'controls'", "'once_per_turn'", "'on'", "'normal_summoned'", 
		"'special_summoned'", "'summoned'", "'normal_or_special_summoned'", "'flip'", 
		"'destroyed_by_battle'", "'sent_to_grave'", "'sent_from_field_to_grave'", 
		"'standby_phase'", "'end_phase'", "'destroys_by_battle'", "'battle_damage'", 
		"'attack_declared'", "'ignition'", "'then'", "'draw'", "'search'", "'deck'", 
		"'revive'", "'destroy'", "'all'", "'target'", "'send_to_grave'", "'gain_lp'", 
		"'burn'", "'equip'", "'special_summon'", "'hand'", "'grave'", "'self'", 
		"'self_grave'", "'return_to_hand'", "'gain_atk'", "'add_to_hand'", "'banished'", 
		"'banish'", "'negate'", "'any'", "'opponent'", "'field'", "'opponent_grave'", 
		"'either_grave'", "'own'", "'where'", "'and'", "'monster'", "'spell'", 
		"'trap'", "'card'", "'race'", "'attribute'", "'level'", "'archetype'", 
		"'name'", "'='", "'<='", "'>='", "'<'", "'>'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, "NUMBER", "IDENT", "STRING", "WS", "LINE_COMMENT"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "EffectScript.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static EffectScriptParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public EffectScriptParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public EffectScriptParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ScriptContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(EffectScriptParser.Eof, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public EffectContext[] effect() {
			return GetRuleContexts<EffectContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public EffectContext effect(int i) {
			return GetRuleContext<EffectContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public EffectBodyContext[] effectBody() {
			return GetRuleContexts<EffectBodyContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public EffectBodyContext effectBody(int i) {
			return GetRuleContext<EffectBodyContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public AsScriptContext asScript() {
			return GetRuleContext<AsScriptContext>(0);
		}
		public ScriptContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_script; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitScript(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ScriptContext script() {
		ScriptContext _localctx = new ScriptContext(Context, State);
		EnterRule(_localctx, 0, RULE_script);
		int _la;
		try {
			State = 106;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__9:
				EnterOuterAlt(_localctx, 1);
				{
				State = 87;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				do {
					{
					{
					State = 86;
					effect();
					}
					}
					State = 89;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				} while ( _la==T__9 );
				State = 91;
				Match(Eof);
				}
				break;
			case T__12:
			case T__21:
			case T__25:
			case T__41:
			case T__42:
			case T__44:
			case T__45:
			case T__48:
			case T__49:
			case T__50:
			case T__51:
			case T__52:
			case T__57:
			case T__58:
			case T__59:
			case T__61:
			case T__62:
				EnterOuterAlt(_localctx, 2);
				{
				State = 93;
				effectBody();
				State = 98;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__0) {
					{
					{
					State = 94;
					Match(T__0);
					State = 95;
					effectBody();
					}
					}
					State = 100;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 101;
				Match(Eof);
				}
				break;
			case T__1:
				EnterOuterAlt(_localctx, 3);
				{
				State = 103;
				asScript();
				State = 104;
				Match(Eof);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AsScriptContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER() { return GetToken(EffectScriptParser.NUMBER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(EffectScriptParser.STRING, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public StatPartContext[] statPart() {
			return GetRuleContexts<StatPartContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatPartContext statPart(int i) {
			return GetRuleContext<StatPartContext>(i);
		}
		public AsScriptContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_asScript; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAsScript(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AsScriptContext asScript() {
		AsScriptContext _localctx = new AsScriptContext(Context, State);
		EnterRule(_localctx, 2, RULE_asScript);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 108;
			Match(T__1);
			State = 109;
			Match(T__2);
			State = 110;
			_la = TokenStream.LA(1);
			if ( !(_la==NUMBER || _la==STRING) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			State = 111;
			Match(T__3);
			State = 121;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__4) {
				{
				State = 112;
				Match(T__4);
				State = 113;
				statPart();
				State = 118;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__5) {
					{
					{
					State = 114;
					Match(T__5);
					State = 115;
					statPart();
					}
					}
					State = 120;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
			}

			State = 124;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__6) {
				{
				State = 123;
				Match(T__6);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StatPartContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER() { return GetToken(EffectScriptParser.NUMBER, 0); }
		public StatPartContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statPart; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStatPart(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StatPartContext statPart() {
		StatPartContext _localctx = new StatPartContext(Context, State);
		EnterRule(_localctx, 4, RULE_statPart);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 126;
			_la = TokenStream.LA(1);
			if ( !(_la==T__7 || _la==T__8) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			State = 127;
			Match(NUMBER);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EffectContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public EffectBodyContext effectBody() {
			return GetRuleContext<EffectBodyContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(EffectScriptParser.STRING, 0); }
		public EffectContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_effect; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEffect(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public EffectContext effect() {
		EffectContext _localctx = new EffectContext(Context, State);
		EnterRule(_localctx, 6, RULE_effect);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 129;
			Match(T__9);
			State = 131;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==STRING) {
				{
				State = 130;
				Match(STRING);
				}
			}

			State = 133;
			Match(T__10);
			State = 134;
			effectBody();
			State = 135;
			Match(T__11);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EffectBodyContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ChainContext chain() {
			return GetRuleContext<ChainContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public TriggerContext trigger() {
			return GetRuleContext<TriggerContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public RequireClauseContext requireClause() {
			return GetRuleContext<RequireClauseContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public CostClauseContext costClause() {
			return GetRuleContext<CostClauseContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public LimitContext limit() {
			return GetRuleContext<LimitContext>(0);
		}
		public EffectBodyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_effectBody; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEffectBody(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public EffectBodyContext effectBody() {
		EffectBodyContext _localctx = new EffectBodyContext(Context, State);
		EnterRule(_localctx, 8, RULE_effectBody);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 138;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__25) {
				{
				State = 137;
				trigger();
				}
			}

			State = 141;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__21) {
				{
				State = 140;
				requireClause();
				}
			}

			State = 144;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__12) {
				{
				State = 143;
				costClause();
				}
			}

			State = 146;
			chain();
			State = 148;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__6) {
				{
				State = 147;
				Match(T__6);
				}
			}

			State = 151;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__24) {
				{
				State = 150;
				limit();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CostClauseContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public DiscardCostContext discardCost() {
			return GetRuleContext<DiscardCostContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public PayCostContext payCost() {
			return GetRuleContext<PayCostContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public SelfCostContext selfCost() {
			return GetRuleContext<SelfCostContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public DetachCostContext detachCost() {
			return GetRuleContext<DetachCostContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public TributeCostContext tributeCost() {
			return GetRuleContext<TributeCostContext>(0);
		}
		public CostClauseContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_costClause; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCostClause(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CostClauseContext costClause() {
		CostClauseContext _localctx = new CostClauseContext(Context, State);
		EnterRule(_localctx, 10, RULE_costClause);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 153;
			Match(T__12);
			State = 159;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__16:
				{
				State = 154;
				discardCost();
				}
				break;
			case T__17:
				{
				State = 155;
				payCost();
				}
				break;
			case T__18:
			case T__19:
			case T__20:
				{
				State = 156;
				selfCost();
				}
				break;
			case T__15:
				{
				State = 157;
				detachCost();
				}
				break;
			case T__14:
				{
				State = 158;
				tributeCost();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			State = 161;
			Match(T__13);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TributeCostContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER() { return GetToken(EffectScriptParser.NUMBER, 0); }
		public TributeCostContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_tributeCost; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTributeCost(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TributeCostContext tributeCost() {
		TributeCostContext _localctx = new TributeCostContext(Context, State);
		EnterRule(_localctx, 12, RULE_tributeCost);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 163;
			Match(T__14);
			State = 164;
			Match(T__2);
			State = 165;
			Match(NUMBER);
			State = 166;
			Match(T__3);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DetachCostContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER() { return GetToken(EffectScriptParser.NUMBER, 0); }
		public DetachCostContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_detachCost; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDetachCost(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DetachCostContext detachCost() {
		DetachCostContext _localctx = new DetachCostContext(Context, State);
		EnterRule(_localctx, 14, RULE_detachCost);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 168;
			Match(T__15);
			State = 169;
			Match(T__2);
			State = 170;
			Match(NUMBER);
			State = 171;
			Match(T__3);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DiscardCostContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER() { return GetToken(EffectScriptParser.NUMBER, 0); }
		public DiscardCostContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_discardCost; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDiscardCost(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DiscardCostContext discardCost() {
		DiscardCostContext _localctx = new DiscardCostContext(Context, State);
		EnterRule(_localctx, 16, RULE_discardCost);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 173;
			Match(T__16);
			State = 174;
			Match(T__2);
			State = 175;
			Match(NUMBER);
			State = 176;
			Match(T__3);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PayCostContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER() { return GetToken(EffectScriptParser.NUMBER, 0); }
		public PayCostContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_payCost; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPayCost(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PayCostContext payCost() {
		PayCostContext _localctx = new PayCostContext(Context, State);
		EnterRule(_localctx, 18, RULE_payCost);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 178;
			Match(T__17);
			State = 179;
			Match(T__2);
			State = 180;
			Match(NUMBER);
			State = 181;
			Match(T__3);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SelfCostContext : ParserRuleContext {
		public SelfCostContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_selfCost; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSelfCost(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SelfCostContext selfCost() {
		SelfCostContext _localctx = new SelfCostContext(Context, State);
		EnterRule(_localctx, 20, RULE_selfCost);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 183;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 3670016L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RequireClauseContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public CondNameContext condName() {
			return GetRuleContext<CondNameContext>(0);
		}
		public RequireClauseContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_requireClause; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRequireClause(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public RequireClauseContext requireClause() {
		RequireClauseContext _localctx = new RequireClauseContext(Context, State);
		EnterRule(_localctx, 22, RULE_requireClause);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 185;
			Match(T__21);
			State = 186;
			condName();
			State = 187;
			Match(T__13);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CondNameContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public SelectorContext selector() {
			return GetRuleContext<SelectorContext>(0);
		}
		public CondNameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_condName; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCondName(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CondNameContext condName() {
		CondNameContext _localctx = new CondNameContext(Context, State);
		EnterRule(_localctx, 24, RULE_condName);
		try {
			State = 195;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__22:
				EnterOuterAlt(_localctx, 1);
				{
				State = 189;
				Match(T__22);
				}
				break;
			case T__23:
				EnterOuterAlt(_localctx, 2);
				{
				State = 190;
				Match(T__23);
				State = 191;
				Match(T__2);
				State = 192;
				selector();
				State = 193;
				Match(T__3);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LimitContext : ParserRuleContext {
		public LimitContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_limit; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLimit(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LimitContext limit() {
		LimitContext _localctx = new LimitContext(Context, State);
		EnterRule(_localctx, 26, RULE_limit);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 197;
			Match(T__24);
			State = 199;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__6) {
				{
				State = 198;
				Match(T__6);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TriggerContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public TriggerNameContext triggerName() {
			return GetRuleContext<TriggerNameContext>(0);
		}
		public TriggerContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_trigger; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTrigger(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TriggerContext trigger() {
		TriggerContext _localctx = new TriggerContext(Context, State);
		EnterRule(_localctx, 28, RULE_trigger);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 201;
			Match(T__25);
			State = 202;
			triggerName();
			State = 203;
			Match(T__13);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TriggerNameContext : ParserRuleContext {
		public TriggerNameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_triggerName; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTriggerName(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TriggerNameContext triggerName() {
		TriggerNameContext _localctx = new TriggerNameContext(Context, State);
		EnterRule(_localctx, 30, RULE_triggerName);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 205;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 2198889037824L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ChainContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ActionContext[] action() {
			return GetRuleContexts<ActionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ActionContext action(int i) {
			return GetRuleContext<ActionContext>(i);
		}
		public ChainContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_chain; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitChain(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ChainContext chain() {
		ChainContext _localctx = new ChainContext(Context, State);
		EnterRule(_localctx, 32, RULE_chain);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 207;
			action();
			State = 212;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__40) {
				{
				{
				State = 208;
				Match(T__40);
				State = 209;
				action();
				}
				}
				State = 214;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ActionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public DrawActionContext drawAction() {
			return GetRuleContext<DrawActionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public SearchActionContext searchAction() {
			return GetRuleContext<SearchActionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ReviveActionContext reviveAction() {
			return GetRuleContext<ReviveActionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public DestroyActionContext destroyAction() {
			return GetRuleContext<DestroyActionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public GainActionContext gainAction() {
			return GetRuleContext<GainActionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public BurnActionContext burnAction() {
			return GetRuleContext<BurnActionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public SendActionContext sendAction() {
			return GetRuleContext<SendActionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public EquipActionContext equipAction() {
			return GetRuleContext<EquipActionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public SummonActionContext summonAction() {
			return GetRuleContext<SummonActionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public SalvageActionContext salvageAction() {
			return GetRuleContext<SalvageActionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public BanishActionContext banishAction() {
			return GetRuleContext<BanishActionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public GainAtkActionContext gainAtkAction() {
			return GetRuleContext<GainAtkActionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ReturnActionContext returnAction() {
			return GetRuleContext<ReturnActionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NegateActionContext negateAction() {
			return GetRuleContext<NegateActionContext>(0);
		}
		public ActionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_action; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAction(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ActionContext action() {
		ActionContext _localctx = new ActionContext(Context, State);
		EnterRule(_localctx, 34, RULE_action);
		try {
			State = 229;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__41:
				EnterOuterAlt(_localctx, 1);
				{
				State = 215;
				drawAction();
				}
				break;
			case T__42:
				EnterOuterAlt(_localctx, 2);
				{
				State = 216;
				searchAction();
				}
				break;
			case T__44:
				EnterOuterAlt(_localctx, 3);
				{
				State = 217;
				reviveAction();
				}
				break;
			case T__45:
				EnterOuterAlt(_localctx, 4);
				{
				State = 218;
				destroyAction();
				}
				break;
			case T__49:
				EnterOuterAlt(_localctx, 5);
				{
				State = 219;
				gainAction();
				}
				break;
			case T__50:
				EnterOuterAlt(_localctx, 6);
				{
				State = 220;
				burnAction();
				}
				break;
			case T__48:
				EnterOuterAlt(_localctx, 7);
				{
				State = 221;
				sendAction();
				}
				break;
			case T__51:
				EnterOuterAlt(_localctx, 8);
				{
				State = 222;
				equipAction();
				}
				break;
			case T__52:
				EnterOuterAlt(_localctx, 9);
				{
				State = 223;
				summonAction();
				}
				break;
			case T__59:
				EnterOuterAlt(_localctx, 10);
				{
				State = 224;
				salvageAction();
				}
				break;
			case T__61:
				EnterOuterAlt(_localctx, 11);
				{
				State = 225;
				banishAction();
				}
				break;
			case T__58:
				EnterOuterAlt(_localctx, 12);
				{
				State = 226;
				gainAtkAction();
				}
				break;
			case T__57:
				EnterOuterAlt(_localctx, 13);
				{
				State = 227;
				returnAction();
				}
				break;
			case T__62:
				EnterOuterAlt(_localctx, 14);
				{
				State = 228;
				negateAction();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DrawActionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER() { return GetToken(EffectScriptParser.NUMBER, 0); }
		public DrawActionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_drawAction; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDrawAction(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DrawActionContext drawAction() {
		DrawActionContext _localctx = new DrawActionContext(Context, State);
		EnterRule(_localctx, 36, RULE_drawAction);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 231;
			Match(T__41);
			State = 232;
			Match(T__2);
			State = 233;
			Match(NUMBER);
			State = 234;
			Match(T__3);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SearchActionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public SelectorContext selector() {
			return GetRuleContext<SelectorContext>(0);
		}
		public SearchActionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_searchAction; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSearchAction(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SearchActionContext searchAction() {
		SearchActionContext _localctx = new SearchActionContext(Context, State);
		EnterRule(_localctx, 38, RULE_searchAction);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 236;
			Match(T__42);
			State = 237;
			Match(T__2);
			State = 238;
			Match(T__43);
			State = 241;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__5) {
				{
				State = 239;
				Match(T__5);
				State = 240;
				selector();
				}
			}

			State = 243;
			Match(T__3);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ReviveActionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public GraveyardContext graveyard() {
			return GetRuleContext<GraveyardContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public SelectorContext selector() {
			return GetRuleContext<SelectorContext>(0);
		}
		public ReviveActionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_reviveAction; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitReviveAction(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ReviveActionContext reviveAction() {
		ReviveActionContext _localctx = new ReviveActionContext(Context, State);
		EnterRule(_localctx, 40, RULE_reviveAction);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 245;
			Match(T__44);
			State = 246;
			Match(T__2);
			State = 247;
			graveyard();
			State = 250;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__5) {
				{
				State = 248;
				Match(T__5);
				State = 249;
				selector();
				}
			}

			State = 252;
			Match(T__3);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DestroyActionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ScopeContext scope() {
			return GetRuleContext<ScopeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public SideContext side() {
			return GetRuleContext<SideContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public SelectorContext selector() {
			return GetRuleContext<SelectorContext>(0);
		}
		public DestroyActionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_destroyAction; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDestroyAction(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DestroyActionContext destroyAction() {
		DestroyActionContext _localctx = new DestroyActionContext(Context, State);
		EnterRule(_localctx, 42, RULE_destroyAction);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 254;
			Match(T__45);
			State = 255;
			Match(T__2);
			State = 256;
			scope();
			State = 259;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,19,Context) ) {
			case 1:
				{
				State = 257;
				Match(T__5);
				State = 258;
				side();
				}
				break;
			}
			State = 263;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__5) {
				{
				State = 261;
				Match(T__5);
				State = 262;
				selector();
				}
			}

			State = 265;
			Match(T__3);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ScopeContext : ParserRuleContext {
		public ScopeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_scope; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitScope(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ScopeContext scope() {
		ScopeContext _localctx = new ScopeContext(Context, State);
		EnterRule(_localctx, 44, RULE_scope);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 267;
			_la = TokenStream.LA(1);
			if ( !(_la==T__46 || _la==T__47) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SendActionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public SelectorContext selector() {
			return GetRuleContext<SelectorContext>(0);
		}
		public SendActionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_sendAction; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSendAction(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SendActionContext sendAction() {
		SendActionContext _localctx = new SendActionContext(Context, State);
		EnterRule(_localctx, 46, RULE_sendAction);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 269;
			Match(T__48);
			State = 270;
			Match(T__2);
			State = 271;
			Match(T__43);
			State = 274;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__5) {
				{
				State = 272;
				Match(T__5);
				State = 273;
				selector();
				}
			}

			State = 276;
			Match(T__3);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class GainActionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER() { return GetToken(EffectScriptParser.NUMBER, 0); }
		public GainActionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_gainAction; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitGainAction(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public GainActionContext gainAction() {
		GainActionContext _localctx = new GainActionContext(Context, State);
		EnterRule(_localctx, 48, RULE_gainAction);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 278;
			Match(T__49);
			State = 279;
			Match(T__2);
			State = 280;
			Match(NUMBER);
			State = 281;
			Match(T__3);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BurnActionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER() { return GetToken(EffectScriptParser.NUMBER, 0); }
		public BurnActionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_burnAction; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBurnAction(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BurnActionContext burnAction() {
		BurnActionContext _localctx = new BurnActionContext(Context, State);
		EnterRule(_localctx, 50, RULE_burnAction);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 283;
			Match(T__50);
			State = 284;
			Match(T__2);
			State = 285;
			Match(NUMBER);
			State = 286;
			Match(T__3);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EquipActionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public StatPartContext[] statPart() {
			return GetRuleContexts<StatPartContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatPartContext statPart(int i) {
			return GetRuleContext<StatPartContext>(i);
		}
		public EquipActionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_equipAction; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEquipAction(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public EquipActionContext equipAction() {
		EquipActionContext _localctx = new EquipActionContext(Context, State);
		EnterRule(_localctx, 52, RULE_equipAction);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 288;
			Match(T__51);
			State = 289;
			Match(T__2);
			State = 290;
			statPart();
			State = 295;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__5) {
				{
				{
				State = 291;
				Match(T__5);
				State = 292;
				statPart();
				}
				}
				State = 297;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 298;
			Match(T__3);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SummonActionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public SummonZoneContext summonZone() {
			return GetRuleContext<SummonZoneContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public SelectorContext selector() {
			return GetRuleContext<SelectorContext>(0);
		}
		public SummonActionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_summonAction; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSummonAction(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SummonActionContext summonAction() {
		SummonActionContext _localctx = new SummonActionContext(Context, State);
		EnterRule(_localctx, 54, RULE_summonAction);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 300;
			Match(T__52);
			State = 301;
			Match(T__2);
			State = 302;
			summonZone();
			State = 305;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__5) {
				{
				State = 303;
				Match(T__5);
				State = 304;
				selector();
				}
			}

			State = 307;
			Match(T__3);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SummonZoneContext : ParserRuleContext {
		public SummonZoneContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_summonZone; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSummonZone(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SummonZoneContext summonZone() {
		SummonZoneContext _localctx = new SummonZoneContext(Context, State);
		EnterRule(_localctx, 56, RULE_summonZone);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 309;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 270233569828274176L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ReturnActionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public SideContext side() {
			return GetRuleContext<SideContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public SelectorContext selector() {
			return GetRuleContext<SelectorContext>(0);
		}
		public ReturnActionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_returnAction; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitReturnAction(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ReturnActionContext returnAction() {
		ReturnActionContext _localctx = new ReturnActionContext(Context, State);
		EnterRule(_localctx, 58, RULE_returnAction);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 311;
			Match(T__57);
			State = 312;
			Match(T__2);
			State = 313;
			Match(T__47);
			State = 316;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,24,Context) ) {
			case 1:
				{
				State = 314;
				Match(T__5);
				State = 315;
				side();
				}
				break;
			}
			State = 320;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__5) {
				{
				State = 318;
				Match(T__5);
				State = 319;
				selector();
				}
			}

			State = 322;
			Match(T__3);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class GainAtkActionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER() { return GetToken(EffectScriptParser.NUMBER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public SideContext side() {
			return GetRuleContext<SideContext>(0);
		}
		public GainAtkActionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_gainAtkAction; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitGainAtkAction(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public GainAtkActionContext gainAtkAction() {
		GainAtkActionContext _localctx = new GainAtkActionContext(Context, State);
		EnterRule(_localctx, 60, RULE_gainAtkAction);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 324;
			Match(T__58);
			State = 325;
			Match(T__2);
			State = 329;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (((((_la - 64)) & ~0x3f) == 0 && ((1L << (_la - 64)) & 35L) != 0)) {
				{
				State = 326;
				side();
				State = 327;
				Match(T__5);
				}
			}

			State = 331;
			Match(NUMBER);
			State = 332;
			Match(T__3);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SalvageActionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public SelectorContext selector() {
			return GetRuleContext<SelectorContext>(0);
		}
		public SalvageActionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_salvageAction; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSalvageAction(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SalvageActionContext salvageAction() {
		SalvageActionContext _localctx = new SalvageActionContext(Context, State);
		EnterRule(_localctx, 62, RULE_salvageAction);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 334;
			Match(T__59);
			State = 335;
			Match(T__2);
			State = 336;
			_la = TokenStream.LA(1);
			if ( !(_la==T__54 || _la==T__60) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			State = 339;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__5) {
				{
				State = 337;
				Match(T__5);
				State = 338;
				selector();
				}
			}

			State = 341;
			Match(T__3);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BanishActionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ScopeContext scope() {
			return GetRuleContext<ScopeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public SideContext side() {
			return GetRuleContext<SideContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public SelectorContext selector() {
			return GetRuleContext<SelectorContext>(0);
		}
		public BanishActionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_banishAction; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBanishAction(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BanishActionContext banishAction() {
		BanishActionContext _localctx = new BanishActionContext(Context, State);
		EnterRule(_localctx, 64, RULE_banishAction);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 343;
			Match(T__61);
			State = 344;
			Match(T__2);
			State = 345;
			scope();
			State = 348;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,28,Context) ) {
			case 1:
				{
				State = 346;
				Match(T__5);
				State = 347;
				side();
				}
				break;
			}
			State = 352;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__5) {
				{
				State = 350;
				Match(T__5);
				State = 351;
				selector();
				}
			}

			State = 354;
			Match(T__3);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NegateActionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public NegateArgContext[] negateArg() {
			return GetRuleContexts<NegateArgContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public NegateArgContext negateArg(int i) {
			return GetRuleContext<NegateArgContext>(i);
		}
		public NegateActionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_negateAction; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNegateAction(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NegateActionContext negateAction() {
		NegateActionContext _localctx = new NegateActionContext(Context, State);
		EnterRule(_localctx, 66, RULE_negateAction);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 356;
			Match(T__62);
			State = 357;
			Match(T__2);
			State = 358;
			negateArg();
			State = 363;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__5) {
				{
				{
				State = 359;
				Match(T__5);
				State = 360;
				negateArg();
				}
				}
				State = 365;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 366;
			Match(T__3);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NegateArgContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENT() { return GetToken(EffectScriptParser.IDENT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER() { return GetToken(EffectScriptParser.NUMBER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(EffectScriptParser.STRING, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public KindContext kind() {
			return GetRuleContext<KindContext>(0);
		}
		public NegateArgContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_negateArg; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNegateArg(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NegateArgContext negateArg() {
		NegateArgContext _localctx = new NegateArgContext(Context, State);
		EnterRule(_localctx, 68, RULE_negateArg);
		try {
			State = 377;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case IDENT:
				EnterOuterAlt(_localctx, 1);
				{
				State = 368;
				Match(IDENT);
				}
				break;
			case NUMBER:
				EnterOuterAlt(_localctx, 2);
				{
				State = 369;
				Match(NUMBER);
				}
				break;
			case STRING:
				EnterOuterAlt(_localctx, 3);
				{
				State = 370;
				Match(STRING);
				}
				break;
			case T__71:
			case T__72:
			case T__73:
			case T__74:
				EnterOuterAlt(_localctx, 4);
				{
				State = 371;
				kind();
				}
				break;
			case T__63:
				EnterOuterAlt(_localctx, 5);
				{
				State = 372;
				Match(T__63);
				}
				break;
			case T__64:
				EnterOuterAlt(_localctx, 6);
				{
				State = 373;
				Match(T__64);
				}
				break;
			case T__65:
				EnterOuterAlt(_localctx, 7);
				{
				State = 374;
				Match(T__65);
				}
				break;
			case T__51:
				EnterOuterAlt(_localctx, 8);
				{
				State = 375;
				Match(T__51);
				}
				break;
			case T__9:
				EnterOuterAlt(_localctx, 9);
				{
				State = 376;
				Match(T__9);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class GraveyardContext : ParserRuleContext {
		public GraveyardContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_graveyard; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitGraveyard(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public GraveyardContext graveyard() {
		GraveyardContext _localctx = new GraveyardContext(Context, State);
		EnterRule(_localctx, 70, RULE_graveyard);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 379;
			_la = TokenStream.LA(1);
			if ( !(((((_la - 55)) & ~0x3f) == 0 && ((1L << (_la - 55)) & 12289L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SideContext : ParserRuleContext {
		public SideContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_side; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSide(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SideContext side() {
		SideContext _localctx = new SideContext(Context, State);
		EnterRule(_localctx, 72, RULE_side);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 381;
			_la = TokenStream.LA(1);
			if ( !(((((_la - 64)) & ~0x3f) == 0 && ((1L << (_la - 64)) & 35L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SelectorContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public KindContext kind() {
			return GetRuleContext<KindContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ConditionContext[] condition() {
			return GetRuleContexts<ConditionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ConditionContext condition(int i) {
			return GetRuleContext<ConditionContext>(i);
		}
		public SelectorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_selector; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSelector(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SelectorContext selector() {
		SelectorContext _localctx = new SelectorContext(Context, State);
		EnterRule(_localctx, 74, RULE_selector);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 406;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__71:
			case T__72:
			case T__73:
			case T__74:
				{
				State = 383;
				kind();
				State = 393;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==T__69) {
					{
					State = 384;
					Match(T__69);
					State = 385;
					condition();
					State = 390;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
					while (_la==T__70) {
						{
						{
						State = 386;
						Match(T__70);
						State = 387;
						condition();
						}
						}
						State = 392;
						ErrorHandler.Sync(this);
						_la = TokenStream.LA(1);
					}
					}
				}

				}
				break;
			case T__7:
			case T__69:
			case T__75:
			case T__76:
			case T__77:
			case T__78:
			case T__79:
				{
				State = 396;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==T__69) {
					{
					State = 395;
					Match(T__69);
					}
				}

				State = 398;
				condition();
				State = 403;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__70) {
					{
					{
					State = 399;
					Match(T__70);
					State = 400;
					condition();
					}
					}
					State = 405;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class KindContext : ParserRuleContext {
		public KindContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_kind; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitKind(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public KindContext kind() {
		KindContext _localctx = new KindContext(Context, State);
		EnterRule(_localctx, 76, RULE_kind);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 408;
			_la = TokenStream.LA(1);
			if ( !(((((_la - 72)) & ~0x3f) == 0 && ((1L << (_la - 72)) & 15L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ConditionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public FieldContext field() {
			return GetRuleContext<FieldContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public OpContext op() {
			return GetRuleContext<OpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public ConditionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_condition; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCondition(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ConditionContext condition() {
		ConditionContext _localctx = new ConditionContext(Context, State);
		EnterRule(_localctx, 78, RULE_condition);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 410;
			field();
			State = 411;
			op();
			State = 412;
			value();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FieldContext : ParserRuleContext {
		public FieldContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_field; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitField(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FieldContext field() {
		FieldContext _localctx = new FieldContext(Context, State);
		EnterRule(_localctx, 80, RULE_field);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 414;
			_la = TokenStream.LA(1);
			if ( !(_la==T__7 || ((((_la - 76)) & ~0x3f) == 0 && ((1L << (_la - 76)) & 31L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OpContext : ParserRuleContext {
		public OpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_op; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOp(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public OpContext op() {
		OpContext _localctx = new OpContext(Context, State);
		EnterRule(_localctx, 82, RULE_op);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 416;
			_la = TokenStream.LA(1);
			if ( !(((((_la - 81)) & ~0x3f) == 0 && ((1L << (_la - 81)) & 31L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ValueContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER() { return GetToken(EffectScriptParser.NUMBER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENT() { return GetToken(EffectScriptParser.IDENT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(EffectScriptParser.STRING, 0); }
		public ValueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_value; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEffectScriptVisitor<TResult> typedVisitor = visitor as IEffectScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitValue(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ValueContext value() {
		ValueContext _localctx = new ValueContext(Context, State);
		EnterRule(_localctx, 84, RULE_value);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 418;
			_la = TokenStream.LA(1);
			if ( !(((((_la - 86)) & ~0x3f) == 0 && ((1L << (_la - 86)) & 7L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static int[] _serializedATN = {
		4,1,90,421,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,7,14,
		2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,2,20,7,20,2,21,7,21,
		2,22,7,22,2,23,7,23,2,24,7,24,2,25,7,25,2,26,7,26,2,27,7,27,2,28,7,28,
		2,29,7,29,2,30,7,30,2,31,7,31,2,32,7,32,2,33,7,33,2,34,7,34,2,35,7,35,
		2,36,7,36,2,37,7,37,2,38,7,38,2,39,7,39,2,40,7,40,2,41,7,41,2,42,7,42,
		1,0,4,0,88,8,0,11,0,12,0,89,1,0,1,0,1,0,1,0,1,0,5,0,97,8,0,10,0,12,0,100,
		9,0,1,0,1,0,1,0,1,0,1,0,3,0,107,8,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,5,
		1,117,8,1,10,1,12,1,120,9,1,3,1,122,8,1,1,1,3,1,125,8,1,1,2,1,2,1,2,1,
		3,1,3,3,3,132,8,3,1,3,1,3,1,3,1,3,1,4,3,4,139,8,4,1,4,3,4,142,8,4,1,4,
		3,4,145,8,4,1,4,1,4,3,4,149,8,4,1,4,3,4,152,8,4,1,5,1,5,1,5,1,5,1,5,1,
		5,3,5,160,8,5,1,5,1,5,1,6,1,6,1,6,1,6,1,6,1,7,1,7,1,7,1,7,1,7,1,8,1,8,
		1,8,1,8,1,8,1,9,1,9,1,9,1,9,1,9,1,10,1,10,1,11,1,11,1,11,1,11,1,12,1,12,
		1,12,1,12,1,12,1,12,3,12,196,8,12,1,13,1,13,3,13,200,8,13,1,14,1,14,1,
		14,1,14,1,15,1,15,1,16,1,16,1,16,5,16,211,8,16,10,16,12,16,214,9,16,1,
		17,1,17,1,17,1,17,1,17,1,17,1,17,1,17,1,17,1,17,1,17,1,17,1,17,1,17,3,
		17,230,8,17,1,18,1,18,1,18,1,18,1,18,1,19,1,19,1,19,1,19,1,19,3,19,242,
		8,19,1,19,1,19,1,20,1,20,1,20,1,20,1,20,3,20,251,8,20,1,20,1,20,1,21,1,
		21,1,21,1,21,1,21,3,21,260,8,21,1,21,1,21,3,21,264,8,21,1,21,1,21,1,22,
		1,22,1,23,1,23,1,23,1,23,1,23,3,23,275,8,23,1,23,1,23,1,24,1,24,1,24,1,
		24,1,24,1,25,1,25,1,25,1,25,1,25,1,26,1,26,1,26,1,26,1,26,5,26,294,8,26,
		10,26,12,26,297,9,26,1,26,1,26,1,27,1,27,1,27,1,27,1,27,3,27,306,8,27,
		1,27,1,27,1,28,1,28,1,29,1,29,1,29,1,29,1,29,3,29,317,8,29,1,29,1,29,3,
		29,321,8,29,1,29,1,29,1,30,1,30,1,30,1,30,1,30,3,30,330,8,30,1,30,1,30,
		1,30,1,31,1,31,1,31,1,31,1,31,3,31,340,8,31,1,31,1,31,1,32,1,32,1,32,1,
		32,1,32,3,32,349,8,32,1,32,1,32,3,32,353,8,32,1,32,1,32,1,33,1,33,1,33,
		1,33,1,33,5,33,362,8,33,10,33,12,33,365,9,33,1,33,1,33,1,34,1,34,1,34,
		1,34,1,34,1,34,1,34,1,34,1,34,3,34,378,8,34,1,35,1,35,1,36,1,36,1,37,1,
		37,1,37,1,37,1,37,5,37,389,8,37,10,37,12,37,392,9,37,3,37,394,8,37,1,37,
		3,37,397,8,37,1,37,1,37,1,37,5,37,402,8,37,10,37,12,37,405,9,37,3,37,407,
		8,37,1,38,1,38,1,39,1,39,1,39,1,39,1,40,1,40,1,41,1,41,1,42,1,42,1,42,
		0,0,43,0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,
		46,48,50,52,54,56,58,60,62,64,66,68,70,72,74,76,78,80,82,84,0,13,2,0,86,
		86,88,88,1,0,8,9,1,0,19,21,1,0,27,40,1,0,47,48,2,0,44,44,54,57,2,0,55,
		55,61,61,2,0,55,55,67,68,2,0,64,65,69,69,1,0,72,75,2,0,8,8,76,80,1,0,81,
		85,1,0,86,88,437,0,106,1,0,0,0,2,108,1,0,0,0,4,126,1,0,0,0,6,129,1,0,0,
		0,8,138,1,0,0,0,10,153,1,0,0,0,12,163,1,0,0,0,14,168,1,0,0,0,16,173,1,
		0,0,0,18,178,1,0,0,0,20,183,1,0,0,0,22,185,1,0,0,0,24,195,1,0,0,0,26,197,
		1,0,0,0,28,201,1,0,0,0,30,205,1,0,0,0,32,207,1,0,0,0,34,229,1,0,0,0,36,
		231,1,0,0,0,38,236,1,0,0,0,40,245,1,0,0,0,42,254,1,0,0,0,44,267,1,0,0,
		0,46,269,1,0,0,0,48,278,1,0,0,0,50,283,1,0,0,0,52,288,1,0,0,0,54,300,1,
		0,0,0,56,309,1,0,0,0,58,311,1,0,0,0,60,324,1,0,0,0,62,334,1,0,0,0,64,343,
		1,0,0,0,66,356,1,0,0,0,68,377,1,0,0,0,70,379,1,0,0,0,72,381,1,0,0,0,74,
		406,1,0,0,0,76,408,1,0,0,0,78,410,1,0,0,0,80,414,1,0,0,0,82,416,1,0,0,
		0,84,418,1,0,0,0,86,88,3,6,3,0,87,86,1,0,0,0,88,89,1,0,0,0,89,87,1,0,0,
		0,89,90,1,0,0,0,90,91,1,0,0,0,91,92,5,0,0,1,92,107,1,0,0,0,93,98,3,8,4,
		0,94,95,5,1,0,0,95,97,3,8,4,0,96,94,1,0,0,0,97,100,1,0,0,0,98,96,1,0,0,
		0,98,99,1,0,0,0,99,101,1,0,0,0,100,98,1,0,0,0,101,102,5,0,0,1,102,107,
		1,0,0,0,103,104,3,2,1,0,104,105,5,0,0,1,105,107,1,0,0,0,106,87,1,0,0,0,
		106,93,1,0,0,0,106,103,1,0,0,0,107,1,1,0,0,0,108,109,5,2,0,0,109,110,5,
		3,0,0,110,111,7,0,0,0,111,121,5,4,0,0,112,113,5,5,0,0,113,118,3,4,2,0,
		114,115,5,6,0,0,115,117,3,4,2,0,116,114,1,0,0,0,117,120,1,0,0,0,118,116,
		1,0,0,0,118,119,1,0,0,0,119,122,1,0,0,0,120,118,1,0,0,0,121,112,1,0,0,
		0,121,122,1,0,0,0,122,124,1,0,0,0,123,125,5,7,0,0,124,123,1,0,0,0,124,
		125,1,0,0,0,125,3,1,0,0,0,126,127,7,1,0,0,127,128,5,86,0,0,128,5,1,0,0,
		0,129,131,5,10,0,0,130,132,5,88,0,0,131,130,1,0,0,0,131,132,1,0,0,0,132,
		133,1,0,0,0,133,134,5,11,0,0,134,135,3,8,4,0,135,136,5,12,0,0,136,7,1,
		0,0,0,137,139,3,28,14,0,138,137,1,0,0,0,138,139,1,0,0,0,139,141,1,0,0,
		0,140,142,3,22,11,0,141,140,1,0,0,0,141,142,1,0,0,0,142,144,1,0,0,0,143,
		145,3,10,5,0,144,143,1,0,0,0,144,145,1,0,0,0,145,146,1,0,0,0,146,148,3,
		32,16,0,147,149,5,7,0,0,148,147,1,0,0,0,148,149,1,0,0,0,149,151,1,0,0,
		0,150,152,3,26,13,0,151,150,1,0,0,0,151,152,1,0,0,0,152,9,1,0,0,0,153,
		159,5,13,0,0,154,160,3,16,8,0,155,160,3,18,9,0,156,160,3,20,10,0,157,160,
		3,14,7,0,158,160,3,12,6,0,159,154,1,0,0,0,159,155,1,0,0,0,159,156,1,0,
		0,0,159,157,1,0,0,0,159,158,1,0,0,0,160,161,1,0,0,0,161,162,5,14,0,0,162,
		11,1,0,0,0,163,164,5,15,0,0,164,165,5,3,0,0,165,166,5,86,0,0,166,167,5,
		4,0,0,167,13,1,0,0,0,168,169,5,16,0,0,169,170,5,3,0,0,170,171,5,86,0,0,
		171,172,5,4,0,0,172,15,1,0,0,0,173,174,5,17,0,0,174,175,5,3,0,0,175,176,
		5,86,0,0,176,177,5,4,0,0,177,17,1,0,0,0,178,179,5,18,0,0,179,180,5,3,0,
		0,180,181,5,86,0,0,181,182,5,4,0,0,182,19,1,0,0,0,183,184,7,2,0,0,184,
		21,1,0,0,0,185,186,5,22,0,0,186,187,3,24,12,0,187,188,5,14,0,0,188,23,
		1,0,0,0,189,196,5,23,0,0,190,191,5,24,0,0,191,192,5,3,0,0,192,193,3,74,
		37,0,193,194,5,4,0,0,194,196,1,0,0,0,195,189,1,0,0,0,195,190,1,0,0,0,196,
		25,1,0,0,0,197,199,5,25,0,0,198,200,5,7,0,0,199,198,1,0,0,0,199,200,1,
		0,0,0,200,27,1,0,0,0,201,202,5,26,0,0,202,203,3,30,15,0,203,204,5,14,0,
		0,204,29,1,0,0,0,205,206,7,3,0,0,206,31,1,0,0,0,207,212,3,34,17,0,208,
		209,5,41,0,0,209,211,3,34,17,0,210,208,1,0,0,0,211,214,1,0,0,0,212,210,
		1,0,0,0,212,213,1,0,0,0,213,33,1,0,0,0,214,212,1,0,0,0,215,230,3,36,18,
		0,216,230,3,38,19,0,217,230,3,40,20,0,218,230,3,42,21,0,219,230,3,48,24,
		0,220,230,3,50,25,0,221,230,3,46,23,0,222,230,3,52,26,0,223,230,3,54,27,
		0,224,230,3,62,31,0,225,230,3,64,32,0,226,230,3,60,30,0,227,230,3,58,29,
		0,228,230,3,66,33,0,229,215,1,0,0,0,229,216,1,0,0,0,229,217,1,0,0,0,229,
		218,1,0,0,0,229,219,1,0,0,0,229,220,1,0,0,0,229,221,1,0,0,0,229,222,1,
		0,0,0,229,223,1,0,0,0,229,224,1,0,0,0,229,225,1,0,0,0,229,226,1,0,0,0,
		229,227,1,0,0,0,229,228,1,0,0,0,230,35,1,0,0,0,231,232,5,42,0,0,232,233,
		5,3,0,0,233,234,5,86,0,0,234,235,5,4,0,0,235,37,1,0,0,0,236,237,5,43,0,
		0,237,238,5,3,0,0,238,241,5,44,0,0,239,240,5,6,0,0,240,242,3,74,37,0,241,
		239,1,0,0,0,241,242,1,0,0,0,242,243,1,0,0,0,243,244,5,4,0,0,244,39,1,0,
		0,0,245,246,5,45,0,0,246,247,5,3,0,0,247,250,3,70,35,0,248,249,5,6,0,0,
		249,251,3,74,37,0,250,248,1,0,0,0,250,251,1,0,0,0,251,252,1,0,0,0,252,
		253,5,4,0,0,253,41,1,0,0,0,254,255,5,46,0,0,255,256,5,3,0,0,256,259,3,
		44,22,0,257,258,5,6,0,0,258,260,3,72,36,0,259,257,1,0,0,0,259,260,1,0,
		0,0,260,263,1,0,0,0,261,262,5,6,0,0,262,264,3,74,37,0,263,261,1,0,0,0,
		263,264,1,0,0,0,264,265,1,0,0,0,265,266,5,4,0,0,266,43,1,0,0,0,267,268,
		7,4,0,0,268,45,1,0,0,0,269,270,5,49,0,0,270,271,5,3,0,0,271,274,5,44,0,
		0,272,273,5,6,0,0,273,275,3,74,37,0,274,272,1,0,0,0,274,275,1,0,0,0,275,
		276,1,0,0,0,276,277,5,4,0,0,277,47,1,0,0,0,278,279,5,50,0,0,279,280,5,
		3,0,0,280,281,5,86,0,0,281,282,5,4,0,0,282,49,1,0,0,0,283,284,5,51,0,0,
		284,285,5,3,0,0,285,286,5,86,0,0,286,287,5,4,0,0,287,51,1,0,0,0,288,289,
		5,52,0,0,289,290,5,3,0,0,290,295,3,4,2,0,291,292,5,6,0,0,292,294,3,4,2,
		0,293,291,1,0,0,0,294,297,1,0,0,0,295,293,1,0,0,0,295,296,1,0,0,0,296,
		298,1,0,0,0,297,295,1,0,0,0,298,299,5,4,0,0,299,53,1,0,0,0,300,301,5,53,
		0,0,301,302,5,3,0,0,302,305,3,56,28,0,303,304,5,6,0,0,304,306,3,74,37,
		0,305,303,1,0,0,0,305,306,1,0,0,0,306,307,1,0,0,0,307,308,5,4,0,0,308,
		55,1,0,0,0,309,310,7,5,0,0,310,57,1,0,0,0,311,312,5,58,0,0,312,313,5,3,
		0,0,313,316,5,48,0,0,314,315,5,6,0,0,315,317,3,72,36,0,316,314,1,0,0,0,
		316,317,1,0,0,0,317,320,1,0,0,0,318,319,5,6,0,0,319,321,3,74,37,0,320,
		318,1,0,0,0,320,321,1,0,0,0,321,322,1,0,0,0,322,323,5,4,0,0,323,59,1,0,
		0,0,324,325,5,59,0,0,325,329,5,3,0,0,326,327,3,72,36,0,327,328,5,6,0,0,
		328,330,1,0,0,0,329,326,1,0,0,0,329,330,1,0,0,0,330,331,1,0,0,0,331,332,
		5,86,0,0,332,333,5,4,0,0,333,61,1,0,0,0,334,335,5,60,0,0,335,336,5,3,0,
		0,336,339,7,6,0,0,337,338,5,6,0,0,338,340,3,74,37,0,339,337,1,0,0,0,339,
		340,1,0,0,0,340,341,1,0,0,0,341,342,5,4,0,0,342,63,1,0,0,0,343,344,5,62,
		0,0,344,345,5,3,0,0,345,348,3,44,22,0,346,347,5,6,0,0,347,349,3,72,36,
		0,348,346,1,0,0,0,348,349,1,0,0,0,349,352,1,0,0,0,350,351,5,6,0,0,351,
		353,3,74,37,0,352,350,1,0,0,0,352,353,1,0,0,0,353,354,1,0,0,0,354,355,
		5,4,0,0,355,65,1,0,0,0,356,357,5,63,0,0,357,358,5,3,0,0,358,363,3,68,34,
		0,359,360,5,6,0,0,360,362,3,68,34,0,361,359,1,0,0,0,362,365,1,0,0,0,363,
		361,1,0,0,0,363,364,1,0,0,0,364,366,1,0,0,0,365,363,1,0,0,0,366,367,5,
		4,0,0,367,67,1,0,0,0,368,378,5,87,0,0,369,378,5,86,0,0,370,378,5,88,0,
		0,371,378,3,76,38,0,372,378,5,64,0,0,373,378,5,65,0,0,374,378,5,66,0,0,
		375,378,5,52,0,0,376,378,5,10,0,0,377,368,1,0,0,0,377,369,1,0,0,0,377,
		370,1,0,0,0,377,371,1,0,0,0,377,372,1,0,0,0,377,373,1,0,0,0,377,374,1,
		0,0,0,377,375,1,0,0,0,377,376,1,0,0,0,378,69,1,0,0,0,379,380,7,7,0,0,380,
		71,1,0,0,0,381,382,7,8,0,0,382,73,1,0,0,0,383,393,3,76,38,0,384,385,5,
		70,0,0,385,390,3,78,39,0,386,387,5,71,0,0,387,389,3,78,39,0,388,386,1,
		0,0,0,389,392,1,0,0,0,390,388,1,0,0,0,390,391,1,0,0,0,391,394,1,0,0,0,
		392,390,1,0,0,0,393,384,1,0,0,0,393,394,1,0,0,0,394,407,1,0,0,0,395,397,
		5,70,0,0,396,395,1,0,0,0,396,397,1,0,0,0,397,398,1,0,0,0,398,403,3,78,
		39,0,399,400,5,71,0,0,400,402,3,78,39,0,401,399,1,0,0,0,402,405,1,0,0,
		0,403,401,1,0,0,0,403,404,1,0,0,0,404,407,1,0,0,0,405,403,1,0,0,0,406,
		383,1,0,0,0,406,396,1,0,0,0,407,75,1,0,0,0,408,409,7,9,0,0,409,77,1,0,
		0,0,410,411,3,80,40,0,411,412,3,82,41,0,412,413,3,84,42,0,413,79,1,0,0,
		0,414,415,7,10,0,0,415,81,1,0,0,0,416,417,7,11,0,0,417,83,1,0,0,0,418,
		419,7,12,0,0,419,85,1,0,0,0,37,89,98,106,118,121,124,131,138,141,144,148,
		151,159,195,199,212,229,241,250,259,263,274,295,305,316,320,329,339,348,
		352,363,377,390,393,396,403,406
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace WolfEx.EffectScriptGenerated
