name: Build and Zip Release

on: push

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v2
        
      - name: Restore NuGet packages
        run: nuget restore WolfX.sln
        
      - name: Build Solution
        run: msbuild WolfX.sln /p:Configuration=Release

      - name: Zip Binaries Folder
        run: Compress-Archive -Path Binaries\* -DestinationPath YuGiOhEX.zip
        
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
            name: Yu-Gi-Oh-Ex-RC
            path: YuGiOhEX.zip
        
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
