name: Build and Zip Release

on:
  push:
    tags:
      - 'v*'  # Triggers only on tags like v1.0, v2.1.3, etc.

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build Solution
      run: msbuild Yu-Gi-Oh-EX.sln /p:Configuration=Release

    - name: Zip Binaries Folder
      run: Compress-Archive -Path Binaries\* -DestinationPath YuGiOhEX.zip

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: YuGiOhEX.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
