name: Build and Zip Release

on: push

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build Solution
        run: msbuild WolfX.sln /p:Configuration=Release

      - name: Zip Binaries Folder
        run: Compress-Archive -Path Binaries\* -DestinationPath YuGiOhEX.zip

      - name: Upload to GitHub Release
        if: github.ref == 'refs/heads/main'  # Only upload on main branch pushes
        uses: softprops/action-gh-release@v1
        with:
          files: YuGiOhEX.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
