name: Build and Release

on:
  push:
    tags:
      - 'v*' # triggers only on tags like v1.0, v2.1 etc.

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build Solution
      run: msbuild Yu-Gi-Oh-EX.sln /p:Configuration=Release

    - name: Upload Release Artifact
      uses: softprops/action-gh-release@v1
      with:
        files: |
          x64/Release/YGOPro.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
